

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PcSborka.Entity
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class CreatePcForThePeopl_dbEntities : DbContext
{
        public static CreatePcForThePeopl_dbEntities DBContext = new CreatePcForThePeopl_dbEntities();
    public CreatePcForThePeopl_dbEntities()
        : base("name=CreatePcForThePeopl_dbEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Case> Case { get; set; }

    public virtual DbSet<Computer> Computer { get; set; }

    public virtual DbSet<Cooler> Cooler { get; set; }

    public virtual DbSet<CPU> CPU { get; set; }

    public virtual DbSet<Employeer> Employeer { get; set; }

    public virtual DbSet<GPU> GPU { get; set; }

    public virtual DbSet<Keyboard> Keyboard { get; set; }

    public virtual DbSet<Monitor> Monitor { get; set; }

    public virtual DbSet<MotherBoard> MotherBoard { get; set; }

    public virtual DbSet<Mouse> Mouse { get; set; }

    public virtual DbSet<Order> Order { get; set; }

    public virtual DbSet<Periphery> Periphery { get; set; }

    public virtual DbSet<PowerSupply> PowerSupply { get; set; }

    public virtual DbSet<RAM> RAM { get; set; }

}

}

