
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PcSborka.Entity
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int ID { get; set; }

    public Nullable<int> EmployeerID { get; set; }

    public int ComputerID { get; set; }

    public Nullable<int> PeripheryID { get; set; }

    public System.DateTime DateOrder { get; set; }

    public Nullable<bool> Accepted { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public Nullable<double> SumOrder { get; set; }



    public virtual Computer Computer { get; set; }

    public virtual Employeer Employeer { get; set; }

    public virtual Periphery Periphery { get; set; }

}

}
